name: Daily Inflation Model Update

on:
  schedule:
    # Run at 6 AM UTC daily
    - cron: '0 6 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update_models:
    name: Run Inflation Models
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Set up environment variables
        env:
          BLS_API_KEY: ${{ secrets.BLS_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          echo "BLS_API_KEY=$BLS_API_KEY" > .env
          echo "FRED_API_KEY=$FRED_API_KEY" >> .env
      
      - name: Run inflation models
        run: |
          python run_inflation_model.py
          echo "Models executed successfully"
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create branch with date
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          TODAY=$(date +'%Y-%m-%d')
          BRANCH_NAME="model-update-${TODAY}"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
      
      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          TODAY=$(date +'%Y-%m-%d')
          git add data/ src/saved_models/ docs/images/
          git commit -m "Daily model update ${TODAY}" -m "Automated model update with latest economic data"
      
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push -u origin $BRANCH_NAME
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Daily model update ${{ env.BRANCH_NAME }}"
          body: |
            # Automated Daily Model Update
            
            This PR contains the latest inflation forecasts generated on $(date +'%Y-%m-%d').
            
            ## Changes include:
            - Updated model predictions in data/predictions/
            - Saved model files in src/saved_models/
            - Updated visualization charts in docs/images/
            
            Automatically generated by the daily model update workflow.
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: automated,model-update
          draft: false
      
      - name: Auto-merge Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: automated,model-update
          MERGE_DELETE_BRANCH: true 